SELECT ID,CLIENT_ID,MIN(DATEDIFF('MONTH', START_DATE,FINISH_DATE))
FROM PROJECT 
GROUP BY ID
HAVING  MIN(DATEDIFF('MONTH', START_DATE,FINISH_DATE)) IN (
SELECT MIN(DATEDIFF('MONTH', START_DATE,FINISH_DATE))
FROM PROJECT) 