CREATE TABLE worker(
ID IDENTITY PRIMARY KEY,
NAME VARCHAR(1000) NOT NULL CHECK(CHAR_LENGTH(NAME)>=2 ),
BIRTHDAY DATE CHECK ((YEAR FROM BIRTHDAY) >= 1900),
LEVEL VARCHAR NOT NULL CHECK(LEVEL IN ('Trainee', 'Junior','Middle','Senior')),
SALARY INT CHECK (SALARY >= 100 AND SALARY <=100000) )

CREATE TABLE client(
id IDENTITY PRIMARY KEY,
name VARCHAR(1000) NOT NULL CHECK (CHAR_LENGTH(NAME)>=2 ))

CREATE TABLE project (
id IDENTITY PRIMARY KEY,
CLIENT_ID BIGINT,
START_DATE DATE,
FINISH_DATE DATE)

CREATE TABLE project_worker(
    project_id BIGINT NOT NULL,
    worker_id BIGINT NOT NULL,    
    FOREIGN KEY(project_id) REFERENCES project(id),
    FOREIGN KEY (worker_id) REFERENCES worker(id),
    PRIMARY KEY (project_id, worker_id))